version: "3.7"

services:
    momentum-db:
        image: mysql:5.7
        volumes:
            - momentum_db:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: momentum
            MYSQL_USER: me
            MYSQL_PASSWORD: password
        ports:
            - 3309:3306

volumes:
    momentum_db: